version: 1.2.{build}
-
    branches:
        only:
            - master
    configuration: Release
    image: Visual Studio 2017 RC
    build:
        verbosity: normal
    test: off
-
    branches:
        except:
            - master
            - documentation
    configuration: Debug
    image: Visual Studio 2017 RC
    build:
        verbosity: normal
    test: off
-
    branches:
        only:
            - dev
    configuration: Debug
    image: Visual Studio 2017 RC
    build:
        verbosity: normal
    test: auto