# Autogenerated  2016-12-28 11:45:19:781091   (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna

write-host "`n"
echo "-------------------------------------------------------"
echo "MCPU Compiler and Library Unit Tests"
echo "-------------------------------------------------------"
write-host "`n"
mstest -testcontainer:".\mcpu.unit-tests.dll"
write-host "`n"
echo "-------------------------------------------------------"
echo "Visit https://github.com/Unknown6656/MCPU/ for"
echo "more information about the MCPU-project"
echo "-------------------------------------------------------"
write-host "`n"
