# Autogenerated  2017-01-20 14:52:04:562839   (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna

param(
    [string]$mode = "internal"
)

write-host "`n"
echo "-------------------------------------------------------"
echo "         MCPU Compiler and Library Unit Tests"
echo "-------------------------------------------------------"
write-host "`n"

if ($mode -eq "internal")
{
    ".\MCPU Tester.exe" -unittests
}
if ($mode -eq "mstest")
{
    mstest -testcontainer:".\mcpu.unit-tests.dll"
}

write-host "`n"
echo "-------------------------------------------------------"
echo "    Visit https://github.com/Unknown6656/MCPU/ for"
echo "	    more information about the MCPU-project"
echo "-------------------------------------------------------"
write-host "`n"
